Pin(Pin.cpu.A0, mode=Pin.ANALOG)
Pin(Pin.cpu.A1, mode=Pin.ANALOG)
Pin(Pin.cpu.A4, mode=Pin.ANALOG)
Pin(Pin.cpu.A6, mode=Pin.ANALOG)
Pin(Pin.cpu.A0, mode=Pin.ANALOG)
Pin(Pin.cpu.A1, mode=Pin.ANALOG)
Pin(Pin.cpu.A4, mode=Pin.IN)
Pin(Pin.cpu.A6, mode=Pin.IN)
<ADCAll>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
True
NotImplementedError
True
True
