ValueError 1
Timer(2, freq=10, prescaler=124, period=25599, mode=UP, div=1)
Timer(2, freq=10, prescaler=124, period=25599, mode=UP, div=1)
Timer(2, freq=10, prescaler=124, period=25599, mode=UP, div=1)
Timer(6, freq=10, prescaler=124, period=25599, mode=UP, div=1)
Timer(6, freq=10, prescaler=124, period=25599, mode=UP, div=1)
Timer(6, freq=10, prescaler=124, period=25599, mode=UP, div=1)
ValueError 8
Timer(9, freq=10, prescaler=124, period=25599, mode=UP, div=1)
Timer(9, freq=10, prescaler=124, period=25599, mode=UP, div=1)
Timer(9, freq=10, prescaler=124, period=25599, mode=UP, div=1)
Timer(10, freq=10, prescaler=124, period=25599, mode=UP, div=1)
Timer(10, freq=10, prescaler=124, period=25599, mode=UP, div=1)
Timer(10, freq=10, prescaler=124, period=25599, mode=UP, div=1)
Timer(11, freq=10, prescaler=124, period=25599, mode=UP, div=1)
Timer(11, freq=10, prescaler=124, period=25599, mode=UP, div=1)
Timer(11, freq=10, prescaler=124, period=25599, mode=UP, div=1)
ValueError 12
